using MarinApp.Agents.Data;
using Microsoft.SemanticKernel.ChatCompletion;

namespace MarinApp.Agents
{
    /// <summary>
    /// Defines the contract for a human proxy agent that facilitates direct interaction between the system and a human user.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The <see cref="IHumanProxy"/> interface extends <see cref="IAgent"/> to provide additional methods for
    /// interacting with a human user in conversational scenarios. Implementations of this interface are responsible
    /// for displaying messages to the user and awaiting user input, typically within a chat or conversational UI.
    /// </para>
    /// <para>
    /// <b>Key Responsibilities:</b>
    /// <list type="bullet">
    ///   <item>
    ///     <description>
    ///       <see cref="PrintUserMessage(string, string)"/>: Displays a message to the human user, supporting various MIME types for content formatting.
    ///     </description>
    ///   </item>
    ///   <item>
    ///     <description>
    ///       <see cref="WaitOnHumanResponseAsync(string?, ChatHistory, CancellationToken)"/>: Asynchronously waits for a response from the human user,
    ///       optionally providing context or a prompt, and returns the user's input as a string.
    ///     </description>
    ///   </item>
    /// </list>
    /// </para>
    /// <para>
    /// <b>Usage Scenario:</b>
    /// <br/>
    /// This interface is typically implemented by components that bridge automated agents and human users, such as
    /// chat UIs, conversational bots with human-in-the-loop workflows, or systems requiring explicit user confirmation
    /// or input during an automated process.
    /// </para>
    /// </remarks>
    public interface IHumanProxy : IAgent
    {
        /// <summary>
        /// Displays a message to the human user.
        /// </summary>
        /// <param name="content">
        /// The message content to display. This may include plain text, markdown, or other formats depending on the <paramref name="mimeType"/>.
        /// </param>
        /// <param name="mimeType">
        /// The MIME type of the content (e.g., <c>text/plain</c>, <c>text/markdown</c>, <c>text/html</c>), which determines how the message is rendered to the user.
        /// </param>
        /// <remarks>
        /// Implementations should ensure that the message is presented to the user in a manner consistent with the specified MIME type.
        /// </remarks>
        void PrintUserMessage(string content, string mimeType);


        /// <summary>
        /// Displays a message to the human user as if it originated from the agent.
        /// </summary>
        /// <param name="content">
        /// The message content to display to the user. This may include plain text, markdown, or other formats depending on the <paramref name="mimeType"/>.
        /// </param>
        /// <param name="mimeType">
        /// The MIME type of the content (e.g., <c>text/plain</c>, <c>text/markdown</c>, <c>text/html</c>), which determines how the message is rendered to the user.
        /// </param>
        /// <remarks>
        /// <para>
        /// This method is intended to be used by implementations to present messages that are generated by the agent, as opposed to messages originating from the user.
        /// The message should be displayed in the user interface in a manner that clearly distinguishes it as an agent message, such as using a different color, alignment, or avatar.
        /// </para>
        /// <para>
        /// The <paramref name="mimeType"/> parameter allows the implementation to render the content appropriately. For example, if the MIME type is <c>text/markdown</c>,
        /// the content should be rendered as markdown; if it is <c>text/html</c>, the content should be rendered as HTML. Implementations should sanitize and validate
        /// the content as appropriate for the specified MIME type to prevent security issues such as cross-site scripting (XSS).
        /// </para>
        /// <para>
        /// This method does not return a value and is expected to perform its operation synchronously. If the display operation is asynchronous or requires user interaction,
        /// consider using an asynchronous pattern or providing feedback to the caller.
        /// </para>
        /// <para>
        /// <b>Example Usage:</b>
        /// <code language="csharp">
        /// // Display a markdown-formatted message from the agent
        /// humanProxy.PrintAgentMessage("**Hello, user!**", "text/markdown");
        /// </code>
        /// </para>
        /// </remarks>
        void PrintAgentMessage(string content, string mimeType);


        /// <summary>
        /// Displays a status message to the human user.
        /// </summary>
        /// <param name="content">
        /// The status message content to display. This may include plain text, markdown, or other formats depending on the <paramref name="mimeType"/>.
        /// </param>
        /// <param name="mimeType">
        /// The MIME type of the content (e.g., <c>text/plain</c>, <c>text/markdown</c>, <c>text/html</c>), which determines how the status message is rendered to the user.
        /// </param>
        /// <remarks>
        /// <para>
        /// This method is intended for displaying transient or informational status messages to the user, such as notifications, progress updates, or system alerts.
        /// Status messages should be visually distinct from regular user or agent messages, for example by using a different color, icon, or placement in the UI.
        /// </para>
        /// <para>
        /// The <paramref name="mimeType"/> parameter allows the implementation to render the content appropriately. For example, if the MIME type is <c>text/markdown</c>,
        /// the content should be rendered as markdown; if it is <c>text/html</c>, the content should be rendered as HTML. Implementations should sanitize and validate
        /// the content as appropriate for the specified MIME type to prevent security issues such as cross-site scripting (XSS).
        /// </para>
        /// <para>
        /// This method does not return a value and is expected to perform its operation synchronously. If the display operation is asynchronous or requires user interaction,
        /// consider using an asynchronous pattern or providing feedback to the caller.
        /// </para>
        /// <para>
        /// <b>Example Usage:</b>
        /// <code language="csharp">
        /// // Display a plain text status message
        /// humanProxy.PrintStatusMessage("Loading, please wait...", "text/plain");
        /// </code>
        /// </para>
        /// </remarks>
        void PrintStatusMessage(string content, string mimeType);

        /// <summary>
        /// Asynchronously waits for a response from the human user.
        /// </summary>
        /// <param name="agentText">
        /// Optional text or prompt from the agent to display to the user, providing context for the expected response.
        /// </param>
        /// <param name="history">
        /// The current <see cref="AgentHistory"/> of the conversation, which may be used to provide additional context or display previous messages to the user.
        /// </param>
        /// <param name="cancellationToken">
        /// A <see cref="CancellationToken"/> that can be used to cancel the wait operation if needed (e.g., if the session is terminated or times out).
        /// </param>
        /// <returns>
        /// A <see cref="Task{TResult}"/> representing the asynchronous operation, with the result being the user's response as a string.
        /// </returns>
        /// <remarks>
        /// Implementations should block or suspend execution until the user provides input, or the operation is cancelled.
        /// The returned string should contain the user's raw input, which may be further processed by the agent or system.
        /// </remarks>
        Task<string> WaitOnHumanResponseAsync(string? agentText, AgentHistory history, CancellationToken cancellationToken);
    }
}